-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgT/3ApoGtofLnFnwy
5aENDZh/Xvg58Hg+/TFcgcvh2YegCgYIKoZIzj0DAQehRANCAAS/b5QvzkzGHAPd
CTA/WQ3/ItnMeQrasKPXyubKClaXQmmpAqrp8YpxT0B3pWJqBo6IW4Ki66Sikz+w
TCW8AaAK
-----END PRIVATE KEY-----